##the qa csv this script looks for as a starting point is generated by /import/speedy/scripts/hopsonr/QA/ASL_QA_v1.sh

####check for config file
print(commandArgs(trailingOnly=TRUE))
qa_path<-commandArgs(trailingOnly=TRUE)[1]
out_path<-commandArgs(trailingOnly=TRUE)[2]
visual_qa<-commandArgs(trailingOnly=TRUE)[3]
redcap_project<-commandArgs(trailingOnly=TRUE)[4]

if (exists("testing")){
      #qa_path<-"/import/monstrum/eons2_xnat/scripts/ASL/QA/automated_qa.csv"
      qa_path<-"/import/monstrum/tripod/scripts/4letter3bk/QA/automated/test.csv"
      #out_path<-"~/ASL_QA_test_data.csv"
      out_path<-"/import/monstrum/tripod/scripts/4letter3bk/QA/automated/test_excludes.csv"
      #visual_qa<-"/import/monstrum/eons2_xnat/redcap/imaging/n404_asl_visual_QA.csv"
      visual_qa<-"/import/monstrum/tripod/scripts/4letter3bk/QA/automated/test_visual.csv"
      #redcap_project<-"PNC-LG_Imaging"
}

###test if arguments are valid
if (! file.exists(qa_path)){stop(paste(qa_path," not found.",sep=""))}else{qa_data<-read.csv(qa_path)}

###set qa vars to 0
qa_data[,c("no_data_exclude","not_processed_exclude","mean_rel_rms_exclude","max_rel_rms_exclude","tsnr_exclude","coverage_flag","signal_out_of_mask_flag","fslcc_flag",
           "total_correct_exclude","easy_correct_exclude","visual_inspection_exclude","inspected")]<-0

qa_data$no_data_exclude<-qa_data$no_data_collected ###exclude participants w/ no data collected
qa_data$not_processed_exclude<-qa_data$missing_data ###exclude participants w/ no data processed
qa_data$mean_rel_rms_exclude[which(qa_data$meanrel > 0.5)]<-1 ###exclude participants w/ higher than 0.5 mean rel rms
qa_data$max_rel_rms_exclude[which(qa_data$maxrel > 6)]<-1 ###exclude participants w/ higher than 8 max rel rms
qa_data$tsnr_exclude[which(qa_data$tsnr < 30)]<-1 ###exclude participants w/ tsnr < 30
qa_data$signal_out_of_mask_flag[which(qa_data$voxels_out_of_mask > 30000)]<-1 ###flag participants w/ > 60000 activated voxels out of MNI brain mask #signal out of mask excluded 0 participants
qa_data$fslcc_flag[which(qa_data$fslcc < 0.7)]<-1 ###flag participants w/ less that 0.7 correlation with MNI brain (not clear that this will be a great measure) #fslcc only excluded 1 participant, and then for neg voxels
#qa_data$coverage_flag[which(qa_data$zeros_in_mask > )] ###currently bad coverage is caught by fslcc
qa_data$total_correct_exclude[which(qa_data$all_trials_correct < qa_data$all_trials_count/2)]<-1 ###exclude participants with less than 50% total correct
qa_data$easy_correct_exclude[which(qa_data$easy_condition_count < (qa_data$easy_condition_count-qa_data$easy_condition_count/10))]<-1 ###exclude participants with less than 90% of easy correct
#all_trials_count,all_trials_correct,easy_condition_count,easy_condition_correct

apply(qa_data[,which(substring(colnames(qa_data),nchar(colnames(qa_data))-3,100)=="flag")],2,function(x) sum(x,na.rm=T))
qa_data$flagged<-apply(qa_data[,which(substring(colnames(qa_data),nchar(colnames(qa_data))-3,100)=="flag")],1,function(x) sum(x,na.rm=T))

if (file.exists(visual_qa)){
      visual_qa_data<-read.csv(visual_qa)
      qa_data$visual_inspection_exclude[which(qa_data$scanid %in% visual_qa_data$scanid)]<-visual_qa_data$visual_inspection_exclude[
            match(qa_data$scanid[which(qa_data$scanid%in% visual_qa_data$scanid)],visual_qa_data$scanid)]
      qa_data$inspected[which(qa_data$scanid %in% visual_qa_data$scanid)]<-visual_qa_data$inspected[
            match(qa_data$scanid[which(qa_data$scanid%in% visual_qa_data$scanid)],visual_qa_data$scanid)]      
}

apply(qa_data[,which(substring(colnames(qa_data),nchar(colnames(qa_data))-6,100)=="exclude")],2,function(x) sum(x,na.rm=T))
qa_data$excluded<-apply(qa_data[,which(substring(colnames(qa_data),nchar(colnames(qa_data))-6,100)=="exclude")],1,function(x) sum(x,na.rm=T))

write.table(qa_data,out_path,row.names=F,quote=F,sep=",")
write.table(qa_data[which(qa_data$flagged>0 & qa_data$excluded==qa_data$visual_inspection_exclude),c("bblid","scanid","flagged","inspected","visual_inspection_exclude")],visual_qa,row.names=F,quote=F,sep=",")

#commandArgs

#source()




