##the qa csv this script looks for as a starting point is generated by /import/speedy/scripts/hopsonr/QA/ASL_QA_v1.sh
library("ggplot2", lib.loc="/import/monstrum2/Applications/R3.1.2/lib64/R/library")

####check for config file
print(commandArgs(trailingOnly=TRUE))
qa_path<-commandArgs(trailingOnly=TRUE)[1]
out_path<-commandArgs(trailingOnly=TRUE)[2]
visual_qa<-commandArgs(trailingOnly=TRUE)[3]
redcap_project<-commandArgs(trailingOnly=TRUE)[4]
meanrelrms_cutoff<-commandArgs(trailingOnly=TRUE)[5]
maxrelrms_cutoff<-commandArgs(trailingOnly=TRUE)[6]
tsnr_cutoff<-commandArgs(trailingOnly=TRUE)[7]

if (exists("testing")){
      #qa_path<-"/import/monstrum/tripod/scripts/4letter3bk/QA/automated/test.csv"
      #out_path<-"/import/monstrum/tripod/scripts/4letter3bk/QA/automated/test_excludes.csv"
      #visual_qa<-"/import/monstrum/tripod/scripts/4letter3bk/QA/automated/test_visual.csv"
      qa_path<-"/import/monstrum/eons3_xnat/qa_test/idemo/idemo_qa_test.csv"
      out_path<-"/import/monstrum/eons3_xnat/qa_test/idemo/qa_data_R.csv"
      visual_qa<-"/import/monstrum/eons3_xnat/qa_test/idemo/qa_data_visual.csv"
      #qa_path<-"/import/monstrum/conte_815814/qa_test/bbl1_fearcondV3R1_2.5x2.5x2.5_176/fearcondV3R1_qa_test.csv"
      #out_path<-"/import/monstrum/conte_815814/qa_test/bbl1_fearcondV3R1_2.5x2.5x2.5_176/qa_data_R.csv"
      #visual_qa<-"/import/monstrum/conte_815814/qa_test/bbl1_fearcondV3R1_2.5x2.5x2.5_176/qa_data_visual.csv"
}

###set defaults if not given
if(is.na(meanrelrms_cutoff)){meanrelrms_cutoff<-0.5}
if(is.na(maxrelrms_cutoff)){maxrelrms_cutoff<-6}
if(is.na(tsnr_cutoff)){tsnr_cutoff<-30}

###test if arguments are valid
if (! file.exists(qa_path)){stop(paste(qa_path," not found.",sep=""))}else{qa_data<-read.csv(qa_path)}

#get output directory (for plots)
out_dir<-dirname(out_path)

###set qa vars to 0
qa_data[,c("no_data_exclude","not_processed_exclude","mean_rel_rms_exclude","max_rel_rms_exclude","tsnr_exclude","coverage_flag","signal_out_of_mask_flag","fslcc_flag",
           "total_correct_exclude","easy_correct_exclude","visual_inspection_exclude","inspected")]<-0

qa_data$no_data_exclude<-qa_data$no_data_collected ###exclude participants w/ no data collected
qa_data$not_processed_exclude<-qa_data$missing_data ###exclude participants w/ no data processed
qa_data$mean_rel_rms_exclude[which(qa_data$meanrel > meanrelrms_cutoff)]<-1 ###exclude participants w/ higher than 0.5 mean rel rms
qa_data$max_rel_rms_exclude[which(qa_data$maxrel > maxrelrms_cutoff)]<-1 ###exclude participants w/ higher than 6 max rel rms
qa_data$tsnr_exclude[which(qa_data$tsnr < tsnr_cutoff)]<-1 ###exclude participants w/ tsnr < 30
qa_data$signal_out_of_mask_flag[which(qa_data$voxels_out_of_mask > 30000)]<-1 ###flag participants w/ > 60000 activated voxels out of MNI brain mask #signal out of mask excluded 0 participants
qa_data$fslcc_flag[which(qa_data$fslcc < 0.7)]<-1 ###flag participants w/ less that 0.7 correlation with MNI brain (not clear that this will be a great measure) #fslcc only excluded 1 participant, and then for neg voxels
qa_data$coverage_flag[which(qa_data$zeros_in_mask > 2000)] <-1 ###currently bad coverage is caught by fslcc

pdf(paste(out_dir,"qa_plots.pdf",sep="/"))
for (measure in colnames(qa_data)[grepl("_behave",colnames(qa_data))]){
      print(measure)
      name<-gsub("_behave$","",measure,perl=T)
      print(name)
      min_name<-paste(name,"_min",sep="")
      qa_data[[paste(name,"_exclude",sep="")]]<-0
      qa_data[[paste(name,"_exclude",sep="")]][which(qa_data[[measure]] < qa_data[[min_name]])]<-1
      print(ggplot(data=qa_data,aes(x=qa_data$scanid,y=qa_data[[measure]]))+geom_point()+
            geom_hline(y=qa_data[[min_name]],colour="red")+ylab(name)+xlab("Scanid")+
            ggtitle(paste("Behavioral QA",name,sep=" "))+
            theme(axis.title.x = element_text(face="bold", size=20),
                  axis.title.y  = element_text(face="bold", size=20),
                  axis.text.x=element_text(size=16),axis.text.y=element_text(size=16),
                  plot.title=element_text(size=24,face="bold")))
}

apply(qa_data[,which(substring(colnames(qa_data),nchar(colnames(qa_data))-3,100)=="flag")],2,function(x) sum(x,na.rm=T))
qa_data$flagged<-apply(qa_data[,which(substring(colnames(qa_data),nchar(colnames(qa_data))-3,100)=="flag")],1,function(x) sum(x,na.rm=T))

if (file.exists(visual_qa)){
      visual_qa_data<-read.csv(visual_qa)
      qa_data$visual_inspection_exclude[which(qa_data$scanid %in% visual_qa_data$scanid)]<-visual_qa_data$visual_inspection_exclude[
            match(qa_data$scanid[which(qa_data$scanid%in% visual_qa_data$scanid)],visual_qa_data$scanid)]
      qa_data$inspected[which(qa_data$scanid %in% visual_qa_data$scanid)]<-visual_qa_data$inspected[
            match(qa_data$scanid[which(qa_data$scanid%in% visual_qa_data$scanid)],visual_qa_data$scanid)]      
}

#plot tsnr, meanrelrms, and tsnr v. meanrelrms
ggplot(data=qa_data,aes(x=qa_data$scanid,y=qa_data$meanrel,label=qa_data$scanid))+
      geom_hline(y=0.5,colour="red")+ylab("Mean Relative RMS")+xlab("Scanid")+
      ggtitle(paste("Mean Relative RMS by Scanid"))+
      theme(axis.title.x = element_text(face="bold", size=20),
            axis.title.y  = element_text(face="bold", size=20),
            axis.text.x=element_text(size=16),axis.text.y=element_text(size=16),
            plot.title=element_text(size=24,face="bold"))+geom_text()
ggplot(data=qa_data,aes(x=qa_data$scanid,y=qa_data$tsnr,label=qa_data$scanid))+
      geom_hline(y=30,colour="red")+ylab("tSNR")+xlab("Scanid")+
      ggtitle(paste("tSNR by Scanid"))+
      theme(axis.title.x = element_text(face="bold", size=20),
            axis.title.y  = element_text(face="bold", size=20),
            axis.text.x=element_text(size=16),axis.text.y=element_text(size=16),
            plot.title=element_text(size=24,face="bold"))+geom_text()
ggplot(data=qa_data,aes(x=qa_data$meanrel,y=qa_data$tsnr))+geom_point()+
      geom_hline(y=30,colour="red")+geom_vline(x=.5,colour="red")+ylab("tSNR")+xlab("Mean Relative RMS")+
      ggtitle(paste("tSNR by Mean Relative RMS"))+
      theme(axis.title.x = element_text(face="bold", size=20),
            axis.title.y  = element_text(face="bold", size=20),
            axis.text.x=element_text(size=16),axis.text.y=element_text(size=16),
            plot.title=element_text(size=24,face="bold"))

dev.off()

apply(qa_data[,which(substring(colnames(qa_data),nchar(colnames(qa_data))-6,100)=="exclude")],2,function(x) sum(x,na.rm=T))
qa_data$excluded<-apply(qa_data[,which(substring(colnames(qa_data),nchar(colnames(qa_data))-6,100)=="exclude")],1,function(x) sum(x,na.rm=T))

write.table(qa_data,out_path,row.names=F,quote=F,sep=",")
write.table(qa_data[which(qa_data$flagged>0 & qa_data$excluded==qa_data$visual_inspection_exclude),c("bblid","scanid","flagged","inspected","visual_inspection_exclude")],visual_qa,row.names=F,quote=F,sep=",")



#commandArgs

#source()




